plugins:
  - name: solidity
  - name: vyper
  - name: foundry
  - name: infura
  - name: tokens
  - name: etherscan
  - name: arbitrum
  - name: evmchains
  
default_ecosystem: ethereum

taiko:
  mainnet:
    transaction_acceptance_timeout: 300

ethereum:
  default_network: mainnet-fork
  mainnet:
    default_provider: infura
  mainnet_fork:
    default_provider: foundry

arbitrum:
  default_network: mainnet-fork
  mainnet:
    default_provider: infura
  mainnet_fork:
    default_provider: foundry

networks:
  custom:
     - name: mainnet                   # Required
       chain_id: 146                   # Required
       ecosystem: sonic            # The ecosystem name, can either be new or an existing
       base_ecosystem_plugin: arbitrum  # The ecosystem base-class, defaults to the default ecosystem
       default_provider: node

node:
  sonic:
    mainnet:
      uri: https://rpc.soniclabs.com
